<script lang="ts">
  import { deleteJson, sendJson } from './api';
  import { abilityKeys, type AbilityKey, type AbilityValues, type CharacterDetail, type CharacterInput, type EquipmentCandidate } from './types';
  import { cappedFlaskValue, goldenSeedIncrease, sacredTearIncrease } from './characterResources';
  import { activeArmorSet, equipmentWeight, evasionFor, missingRequirements } from './characterEquipment';
  import EquipmentSkillSummary from './EquipmentSkillSummary.svelte';
  import SkillHoverDetail from './SkillHoverDetail.svelte';
  import InlineNumberEdit from './InlineNumberEdit.svelte';
  import { weaponDamage } from './weaponDamage';
  import { toPng } from 'html-to-image';

  export let character:CharacterDetail;
  export let onUpdated:(character:CharacterDetail)=>void=()=>{};

  const labels:Record<AbilityKey,string>={vigor:'生命力',mind:'精神力',endurance:'持久力',strength:'筋力',dexterity:'技量',intelligence:'知力',faith:'信仰',arcane:'神秘'};
  const toInput=(value:CharacterDetail):CharacterInput=>({name:value.name,adventureId:value.adventureId,originId:value.originId,level:value.level,runes:value.runes,materialPoints:value.materialPoints,growth:Object.fromEntries(abilityKeys.map(key=>[key,value.abilities[key].growth])) as AbilityValues,bonus:Object.fromEntries(abilityKeys.map(key=>[key,value.abilities[key].bonus])) as AbilityValues,resources:{...value.resources}});
  let form=toInput(character),busy=false,exporting=false,errorMessage='',successMessage='',sheetElement:HTMLFormElement;
  let picker:''|'equipment'|'head'|'body'|'talismans'|'skillSets'|'skills'='',equipmentQuery='',skillQuery='';
  let editingAbility:{key:AbilityKey;field:'growth'|'bonus'}|null=null;

  $: currentAbilities=Object.fromEntries(abilityKeys.map(key=>[key,character.abilities[key].initial+form.growth[key]+form.bonus[key]])) as AbilityValues;
  $: totalWeight=equipmentWeight(character.equipment);
  $: evasion=evasionFor(currentAbilities.endurance,totalWeight);
  $: activeSet=activeArmorSet(character.equipment);
  $: armorItems=[character.equipment.armors.head,character.equipment.armors.body].filter(Boolean) as NonNullable<typeof character.equipment.armors.head>[];
  $: armorSets=armorItems.map(item=>item.armorSet).filter((set,index,sets)=>set!==null&&sets.findIndex(candidate=>candidate?.id===set.id)===index) as NonNullable<typeof armorItems[number]['armorSet']>[];
  $: armorTotals={weight:armorItems.reduce((sum,item)=>sum+item.weight,0),physical:armorItems.reduce((sum,item)=>sum+item.physicalCut,0),phenomenon:armorItems.reduce((sum,item)=>sum+item.phenomenonCut,0),poise:armorItems.reduce((sum,item)=>sum+item.poise,0)};
  $: talismanMax=1+character.adventureResources.talismanPouches;
  $: skillMax=2+character.adventureResources.memoryStones;
  $: abilityModifiers=Object.fromEntries(abilityKeys.map(key=>[key,abilityModifier(key)])) as AbilityValues;
  $: equipmentOptions=[...character.inventoryOptions.weapons,...character.inventoryOptions.shields];
  $: filteredEquipmentOptions=equipmentOptions.filter(item=>[item.name,item.categoryName,item.powerModifier,...(item.skills??[]).map(skill=>skill.name)].join(' ').toLocaleLowerCase().includes(equipmentQuery.trim().toLocaleLowerCase()));

  function abilityModifier(key:AbilityKey){return Math.floor(currentAbilities[key]/4);}
  function flaskTotal(){return cappedFlaskValue(goldenSeedIncrease(character.adventureResources.goldenSeeds),form.resources.flaskTotalModifier);}
  function refresh(value:CharacterDetail){character=value;form=toInput(value);onUpdated(value);}
  async function persist(showMessage=false){const saved=await sendJson<CharacterDetail>(`/api/characters/${character.id}`,'PUT',form);refresh(saved);if(showMessage)successMessage='キャラクターの変更を保存しました。';return saved;}
  async function save(){busy=true;errorMessage='';successMessage='';try{await persist(true);}catch(error){errorMessage=error instanceof Error?error.message:'保存できませんでした。';}finally{busy=false;}}
  async function mutate(path:string,method:'POST'|'PUT'|'DELETE',payload?:unknown){busy=true;errorMessage='';successMessage='';try{await persist();const updated=method==='DELETE'?await deleteJson<CharacterDetail>(path):await sendJson<CharacterDetail>(path,method,payload??{});refresh(updated);picker='';successMessage='変更を反映しました。';}catch(error){errorMessage=error instanceof Error?error.message:'変更できませんでした。';}finally{busy=false;}}
  function setFlaskAllocation(kind:'crimson'|'cerulean',rawValue:number){const value=Math.max(0,Math.trunc(Number(rawValue)||0)),other=kind==='crimson'?form.resources.ceruleanFlaskAllocation:form.resources.crimsonFlaskAllocation,next=Math.min(value,Math.max(0,flaskTotal()-other));if(kind==='crimson')form.resources.crimsonFlaskAllocation=next;else form.resources.ceruleanFlaskAllocation=next;form={...form,resources:{...form.resources}};}
  function setFlaskTotalModifier(rawValue:number){form.resources.flaskTotalModifier=Math.trunc(Number(rawValue)||0);const total=flaskTotal();form.resources.crimsonFlaskAllocation=Math.min(form.resources.crimsonFlaskAllocation,total);form.resources.ceruleanFlaskAllocation=Math.min(form.resources.ceruleanFlaskAllocation,Math.max(0,total-form.resources.crimsonFlaskAllocation));form={...form,resources:{...form.resources}};}
  function optionsForPicker():EquipmentCandidate[]{if(picker==='equipment')return filteredEquipmentOptions;if(picker==='head'||picker==='body')return character.inventoryOptions.armors.filter(item=>item.slot===picker.toUpperCase());if(picker==='talismans')return character.inventoryOptions.talismans;return[];}
  function equipOption(item:EquipmentCandidate){if(picker==='equipment')void mutate(`/api/characters/${character.id}/${item.kind==='shield'?'shields':'weapons'}`,'POST',{itemId:item.id});else if(picker==='head'||picker==='body')void mutate(`/api/characters/${character.id}/armors/${picker}`,'PUT',{itemId:item.id});else if(picker==='talismans')void mutate(`/api/characters/${character.id}/talismans`,'POST',{itemId:item.id});}
  function skillMatches(skill:CharacterDetail['learnedSkillSets'][number]['skills'][number]){const query=skillQuery.trim().toLocaleLowerCase();return !query||[skill.name,skill.classification,skill.timing,skill.target,skill.cost,...skill.rankEffects,...skill.weaponCategories.map(item=>item.name),...skill.shieldCategories.map(item=>item.name)].join(' ').toLocaleLowerCase().includes(query);}
  function focusNumber(node:HTMLInputElement){queueMicrotask(()=>{node.focus();node.select();});}
  function editAbility(key:AbilityKey,field:'growth'|'bonus'){editingAbility={key,field};}
  function finishAbilityEdit(){editingAbility=null;form={...form,growth:{...form.growth},bonus:{...form.bonus}};}
  async function exportImage(){
    exporting=true;errorMessage='';successMessage='';
    try{
      editingAbility=null;
      await document.fonts?.ready;
      const dataUrl=await toPng(sheetElement,{backgroundColor:'#201e17',pixelRatio:2,cacheBust:true,filter:(node)=>!(node instanceof HTMLElement&&node.dataset.exportIgnore==='true')});
      const link=document.createElement('a'),safeName=character.name.replace(/[\\/:*?"<>|]/g,'_').trim()||`character-${character.id}`;
      link.download=`${safeName}.png`;link.href=dataUrl;link.click();
      successMessage='キャラクター詳細を画像として保存しました。';
    }catch(error){errorMessage=error instanceof Error?`画像を保存できませんでした。${error.message}`:'画像を保存できませんでした。';}
    finally{exporting=false;}
  }
</script>

{#if errorMessage}<div class="notice notice--error" role="alert">{errorMessage}</div>{/if}
{#if successMessage}<div class="notice notice--success" role="status">{successMessage}</div>{/if}
<form bind:this={sheetElement} class="card character-sheet" onsubmit={(event)=>{event.preventDefault();void save();}}>
  <div class="panel-heading"><div><p class="eyebrow">CHARACTER RECORD</p><h2>{character.name}</h2><p class="muted">LV. {character.level} · {character.originName} · {character.adventureName}</p></div><div class="character-sheet-actions"><button type="button" class="button button--quiet" data-export-ignore="true" disabled={busy||exporting} onclick={()=>void exportImage()}>{exporting?'画像を作成中…':'画像として保存'}</button><button class="button button--primary" disabled={busy||exporting}>変更を保存</button></div></div>
  <div class="resource-row"><label>ルーン<InlineNumberEdit ariaLabel="ルーン" min={0} bind:value={form.runes}/></label><label>素材点<InlineNumberEdit ariaLabel="素材点" min={0} bind:value={form.materialPoints}/></label></div>
  <div class="character-detail-columns">
    <div class="character-detail-left">
      <section class="ability-section"><h3>能力値と能力値補正</h3><div class="ability-table-wrap"><table class="ability-table"><thead><tr><th>能力値</th><th>初期値</th><th>成長値</th><th>追加値</th><th>現在値</th><th>補正</th></tr></thead><tbody>{#each abilityKeys as key}<tr><th>{labels[key]}</th><td class="ability-table__base-value">{character.abilities[key].initial}</td><td class="ability-table__editable">{#if editingAbility?.key===key&&editingAbility.field==='growth'}<input use:focusNumber aria-label={`${labels[key]}の成長値`} type="number" min="0" bind:value={form.growth[key]} onblur={finishAbilityEdit} onkeydown={(event)=>{if(event.key==='Enter')(event.currentTarget as HTMLInputElement).blur();}}>{:else}<button type="button" aria-label={`${labels[key]}の成長値を編集`} onclick={()=>editAbility(key,'growth')}>{form.growth[key]}</button>{/if}</td><td class="ability-table__editable">{#if editingAbility?.key===key&&editingAbility.field==='bonus'}<input use:focusNumber aria-label={`${labels[key]}の追加値`} type="number" bind:value={form.bonus[key]} onblur={finishAbilityEdit} onkeydown={(event)=>{if(event.key==='Enter')(event.currentTarget as HTMLInputElement).blur();}}>{:else}<button type="button" aria-label={`${labels[key]}の追加値を編集`} onclick={()=>editAbility(key,'bonus')}>{form.bonus[key]}</button>{/if}</td><td class="ability-table__total">{currentAbilities[key]}</td><td class="ability-table__modifier">{abilityModifier(key)}</td></tr>{/each}</tbody></table></div></section>
      <section class="character-resources"><h3>リソース</h3><div class="ability-table-wrap"><table class="resource-table resource-table--compact"><thead><tr><th>リソース</th><th>基本値</th><th>補正</th><th>修正値</th><th>合計値</th></tr></thead><tbody><tr><th>最大HP</th><td>5</td><td>{abilityModifier('vigor')}</td><td class="resource-table__editable"><InlineNumberEdit compact ariaLabel="最大HPの修正値" bind:value={form.resources.maxHpModifier}/></td><td class="resource-table__total">{5+abilityModifier('vigor')+form.resources.maxHpModifier}</td></tr><tr><th>最大FP</th><td>5</td><td>{abilityModifier('mind')}</td><td class="resource-table__editable"><InlineNumberEdit compact ariaLabel="最大FPの修正値" bind:value={form.resources.maxFpModifier}/></td><td class="resource-table__total">{5+abilityModifier('mind')+form.resources.maxFpModifier}</td></tr><tr><th>最大加護</th><td>5</td><td>{abilityModifier('arcane')}</td><td class="resource-table__editable"><InlineNumberEdit compact ariaLabel="最大加護の修正値" bind:value={form.resources.maxBlessingModifier}/></td><td class="resource-table__total">{5+abilityModifier('arcane')+form.resources.maxBlessingModifier}</td></tr></tbody></table></div>
        <section class="flask-section"><h4>聖杯瓶振り分け</h4><div class="flask-grid"><article class="flask-card flask-card--total"><h5>合計値</h5><div class="flask-value"><strong>{flaskTotal()}</strong><small>基本値4 + 黄金の種子による増加 {goldenSeedIncrease(character.adventureResources.goldenSeeds)} + 修正値 {form.resources.flaskTotalModifier}、上限10</small></div><label>修正値<InlineNumberEdit ariaLabel="聖杯瓶合計の修正値" value={form.resources.flaskTotalModifier} onChange={setFlaskTotalModifier}/></label></article><article class="flask-card"><h5>緋色の聖杯瓶</h5><div class="flask-value"><strong>{cappedFlaskValue(sacredTearIncrease(character.adventureResources.sacredTears),form.resources.crimsonFlaskHealModifier)}</strong><small>基本値4 + 聖杯の雫による増加 {sacredTearIncrease(character.adventureResources.sacredTears)} + 修正値 {form.resources.crimsonFlaskHealModifier}、上限10</small></div><label>回復量修正<InlineNumberEdit ariaLabel="緋色の聖杯瓶の回復量修正" bind:value={form.resources.crimsonFlaskHealModifier}/></label><label>振り分け数<InlineNumberEdit ariaLabel="緋色の聖杯瓶の振り分け数" min={0} value={form.resources.crimsonFlaskAllocation} onChange={(value)=>setFlaskAllocation('crimson',value)}/></label></article><article class="flask-card"><h5>青色の聖杯瓶</h5><div class="flask-value"><strong>{cappedFlaskValue(sacredTearIncrease(character.adventureResources.sacredTears),form.resources.ceruleanFlaskHealModifier)}</strong><small>基本値4 + 聖杯の雫による増加 {sacredTearIncrease(character.adventureResources.sacredTears)} + 修正値 {form.resources.ceruleanFlaskHealModifier}、上限10</small></div><label>回復量修正<InlineNumberEdit ariaLabel="青色の聖杯瓶の回復量修正" bind:value={form.resources.ceruleanFlaskHealModifier}/></label><label>振り分け数<InlineNumberEdit ariaLabel="青色の聖杯瓶の振り分け数" min={0} value={form.resources.ceruleanFlaskAllocation} onChange={(value)=>setFlaskAllocation('cerulean',value)}/></label></article></div><p class="flask-allocation-summary">振り分け済み <strong>{form.resources.crimsonFlaskAllocation+form.resources.ceruleanFlaskAllocation}</strong> / {flaskTotal()}</p></section>
      </section>
    </div>
    <div class="character-detail-right">
      <section class="loadout-section"><h3>武器・盾</h3>{#each character.equipment.weaponCategories as category}<article class="equipment-category"><header><strong>{category.name}</strong><dl class="equipment-performance"><div><dt>アタックコスト</dt><dd>{category.attackCost}</dd><dt>物理カット</dt><dd>{category.physicalGuard||'不可'}</dd></div><div><dt>ガードコスト</dt><dd>{category.guardCost}</dd><dt>現象カット</dt><dd>{category.phenomenonGuard||'不可'}</dd></div></dl></header>{#if category.skills.length}<div class="category-skills"><small>装備スキル</small>{#each category.skills as skill}<SkillHoverDetail {skill}/>{/each}</div>{/if}{#each category.weapons as weapon}<article class="weapon-entry"><div class="equipped-item"><div><span>重量 {weapon.weight}</span><strong>{weapon.name}{weapon.reinforcementLevel>0?`＋${weapon.reinforcementLevel}`:''}</strong><span>威力補正 {weapon.powerModifier}</span></div><div class="reinforcement-controls"><button type="button" class="button button--quiet" aria-label={`${weapon.name}を強化する`} onclick={()=>void mutate(`/api/characters/${character.id}/weapons/${weapon.slotId}`,'PUT',{reinforcementLevel:weapon.reinforcementLevel+1})}>強化</button><button type="button" class="button button--quiet" onclick={()=>void mutate(`/api/characters/${character.id}/weapons/${weapon.slotId}`,'DELETE')}>外す</button></div></div><div class="compact-damage-table"><span></span>{#each [1,2,3,4,5] as hit}<span>{hit} hit</span>{/each}<strong>片手</strong>{#each category.oneHandDamage as damage}<span>{weaponDamage(damage,weapon.powerModifier,weapon.reinforcementLevel,abilityModifiers)}</span>{/each}<strong>両手</strong>{#each category.twoHandDamage as damage}<span>{weaponDamage(damage,weapon.powerModifier,weapon.reinforcementLevel,abilityModifiers)}</span>{/each}</div>{#each weapon.skills as skill}<EquipmentSkillSummary {skill}/>{/each}</article>{/each}</article>{/each}
        {#if character.equipment.shields.length}<article class="equipment-category"><header><strong>盾</strong></header>{#each character.equipment.shields as shield}<article class="equipped-item"><div><span>重量 {shield.weight}</span><strong>{shield.name}</strong><span>{shield.categoryName}</span><dl class="equipment-performance equipment-performance--item"><div><dt>ガードコスト</dt><dd>{shield.guardCost}</dd><dt>物理カット</dt><dd>{shield.physicalGuard}</dd></div><div><dt></dt><dd></dd><dt>現象カット</dt><dd>{shield.phenomenonGuard}</dd></div></dl></div><button type="button" class="button button--quiet" onclick={()=>void mutate(`/api/characters/${character.id}/shields/${shield.slotId}`,'DELETE')}>外す</button></article>{#each shield.skills as skill}<EquipmentSkillSummary {skill}/>{/each}{/each}</article>{/if}
        <button type="button" class="button button--quiet add-row" onclick={()=>{picker='equipment';equipmentQuery='';}}>追加</button></section>

      <section class="loadout-section"><h3>防具</h3><div class="ability-table-wrap"><table class="armor-table"><thead><tr><th>部位・防具</th><th>重量</th><th>物理防護</th><th>現象防護</th><th>強靭値</th><th>操作</th></tr></thead><tbody>{#each [['head','頭'],['body','胴体']] as slot}{@const armor=character.equipment.armors[slot[0] as 'head'|'body']}<tr><th>{slot[1]}<small>{armor?.name??'未装備'}</small></th><td>{armor?.weight??'—'}</td><td>{armor?.physicalCut??'—'}</td><td>{armor?.phenomenonCut??'—'}</td><td>{armor?`☆×${armor.poise}`:'—'}</td><td><button type="button" class="text-button" onclick={()=>picker=slot[0] as 'head'|'body'}>{armor?'交換':'装備'}</button>{#if armor}<button type="button" class="text-button" onclick={()=>void mutate(`/api/characters/${character.id}/armors/${slot[0]}`,'DELETE')}>外す</button>{/if}</td></tr>{/each}<tr class="armor-total-row"><th>合計</th><td>{armorTotals.weight}</td><td>{armorTotals.physical}</td><td>{armorTotals.phenomenon}</td><td>☆×{armorTotals.poise}</td><td></td></tr></tbody></table></div><div class="armor-effects">{#each armorItems as armor}{#each armor.skills as skill}<div class="armor-effect-source"><small>{armor.name}</small><EquipmentSkillSummary {skill}/></div>{/each}{/each}{#each armorSets as armorSet}<div class:active-set={activeSet?.id===armorSet.id} class="series-effect"><strong>{armorSet.name} — {activeSet?.id===armorSet.id?'発動中':'未発動'}</strong>{#if armorSet.seriesEffect}<p>{armorSet.seriesEffect}</p>{/if}</div>{/each}{#if activeSet&&activeSet.skills.length}{#each activeSet.skills as skill}<div class="armor-effect-source"><small>{activeSet.name} セットスキル</small><EquipmentSkillSummary {skill}/></div>{/each}{/if}</div></section>

      <section class="loadout-section"><div class="section-heading-inline"><h3>タリスマン</h3><span>{character.equipment.talismans.length} / {talismanMax}</span></div>{#each character.equipment.talismans as talisman}<article class="equipped-item"><div><span>重量 {talisman.weight}</span><strong>{talisman.name}</strong><p>{talisman.effect}</p></div><button type="button" class="button button--quiet" onclick={()=>void mutate(`/api/characters/${character.id}/talismans/${talisman.slotId}`,'DELETE')}>外す</button></article>{/each}<button type="button" class="button button--quiet add-row" disabled={character.equipment.talismans.length>=talismanMax} onclick={()=>picker='talismans'}>追加</button></section>

      <section class="loadout-section weight-summary"><h3>合計重量＆回避コスト</h3><div><strong>{totalWeight}</strong><span>（{evasion.label}）</span></div><p>{evasion.cost===null?'回避不可':`回避コスト ${evasion.cost}`}</p></section>

      <section class="loadout-section"><h3>スキルセット</h3>{#each character.learnedSkillSets as set}<article class="skill-set-summary"><strong>{set.name}</strong>{#if set.notes}<p>{set.notes}</p>{/if}</article>{/each}<button type="button" class="button button--quiet add-row" onclick={()=>picker='skillSets'}>追加の習得</button></section>

      <section class="loadout-section"><div class="section-heading-inline"><h3>スキル</h3><span>{character.learnedSkills.length} / {skillMax}</span></div>{#each character.learnedSkills as skill}<article class="learned-skill"><header><div><strong>{skill.name}</strong><span>ランク {skill.rank}</span></div><div><button type="button" class="text-button" disabled={skill.rank>=skill.highestRank} onclick={()=>void mutate(`/api/characters/${character.id}/skills/${skill.rowId}`,'PUT')}>ランクアップ</button><button type="button" class="text-button" onclick={()=>void mutate(`/api/characters/${character.id}/skills/${skill.rowId}`,'DELETE')}>削除</button></div></header><dl><div><dt>分類</dt><dd>{skill.classification}</dd></div><div><dt>タイミング</dt><dd>{skill.timing}</dd></div><div><dt>対象</dt><dd>{skill.target}</dd></div><div><dt>コスト</dt><dd>{skill.cost}</dd></div>{#if skill.maxUses!==null}<div><dt>最大使用回数</dt><dd>{skill.maxUses}</dd></div>{/if}<div><dt>対応カテゴリ</dt><dd>{[...skill.weaponCategories,...skill.shieldCategories].map(item=>item.name).join('、')||'指定なし'}</dd></div></dl>{#each skill.rankEffects as effect,index}{#if effect}<section class:unlearned-rank={index+1>skill.rank} class="rank-effect"><strong>ランク {index+1}</strong><p>{effect}</p></section>{/if}{/each}</article>{/each}<button type="button" class="button button--quiet add-row" disabled={character.learnedSkills.length>=skillMax} onclick={()=>{picker='skills';skillQuery='';}}>スキルを習得</button></section>
    </div>
  </div>
</form>

{#if picker}<div class="modal-backdrop" role="presentation" onclick={(event)=>{if(event.target===event.currentTarget)picker='';}}><section class="card equipment-picker" role="dialog" aria-modal="true"><div class="panel-heading"><div><p class="eyebrow">SELECT</p><h2>{picker==='skillSets'?'スキルセットを習得':picker==='skills'?'スキルを習得':'装備を選択'}</h2></div><button type="button" class="button button--quiet" onclick={()=>picker=''}>閉じる</button></div>
  {#if picker==='skillSets'}<div class="picker-list">{#each character.inventoryOptions.skillSets as set}<button type="button" onclick={()=>void mutate(`/api/characters/${character.id}/skill-sets`,'POST',{itemId:set.id})}><strong>{set.name}</strong><span>所持 {set.quantity}</span><small>{set.notes}</small></button>{/each}</div>
  {:else if picker==='skills'}<label class="picker-search"><span>スキルを検索</span><input type="search" bind:value={skillQuery} placeholder="名前・分類・効果など"></label><div class="picker-skill-sets">{#each character.learnedSkillSets as set}{@const matchingSkills=set.skills.filter(skillMatches)}{#if matchingSkills.length}<section><h3>{set.name}</h3>{#each matchingSkills as skill}{@const learned=character.learnedSkills.some(item=>item.id===skill.id)}<div class="picker-skill-option" class:disabled={learned}><button type="button" disabled={learned} onclick={()=>void mutate(`/api/characters/${character.id}/skills`,'POST',{itemId:skill.id})}><strong>{skill.name}</strong><span>{learned?'習得済み':`${skill.classification} · ${skill.timing}`}</span></button><SkillHoverDetail {skill}/></div>{/each}</section>{/if}{/each}</div>
  {:else}{#if picker==='equipment'}<label class="picker-search"><span>武器・盾を検索</span><input type="search" bind:value={equipmentQuery} placeholder="名前・カテゴリ・スキルなど"></label>{/if}<div class="picker-list">{#each optionsForPicker() as item}{@const missing=missingRequirements(item,currentAbilities)}<article class:unavailable={missing.length>0} class="picker-option"><button type="button" disabled={missing.length>0} onclick={()=>equipOption(item)}><strong>{item.name}</strong><span>{picker==='equipment'?(item.kind==='shield'?'盾 · ':'武器 · '):''}{item.categoryName??item.slot??''} · 重量 {item.weight} · 所持 {item.quantity}{item.powerModifier?` · 威力補正 ${item.powerModifier}`:''}</span>{#each missing as requirement}<small>{labels[requirement.key]}が必要値に足りていません。要求：{requirement.required} 現在値：{requirement.current}</small>{/each}</button>{#if item.skills?.length}<div class="picker-option-skills"><small>装備スキル</small>{#each item.skills as skill}<SkillHoverDetail {skill}/>{/each}</div>{/if}</article>{/each}</div>{/if}
  {#if (picker==='skillSets'&&!character.inventoryOptions.skillSets.length)||(picker==='skills'&&!character.learnedSkillSets.length)||(!['skillSets','skills'].includes(picker)&&!optionsForPicker().length)}<p class="empty-state">選択できる項目はありません。</p>{/if}
</section></div>{/if}
